# mrhandy 1.2.1
# ----------------------------------------------------
# A proprietary tooling to generate Handjet web fonts
# for the Rosetta foundry website. If you are updating
# or compiling Handjet fonts from sources you need not
# worry about this script/config file :)
# ----------------------------------------------------
- name: desktop
  tasks:
    - $ mkdir fonts/HandjetVariable
    - $ cp fonts/Handjet[ELGR,ELSH,wght].ttf fonts/HandjetVariable/HandjetVF-All.ttf
    - .post.update_names:
        style_name: All
- name: desktop
  source: [fonts/HandjetVariable]
  family: [Handjet Variable]
  tasks:
    - .post.update_names:
        style_name: All
- name: web
  source: [fonts/HandjetVariable]
  family: [Handjet Variable Web]
  tasks:
    - .post.make_webfonts
- name: preview
  source: [fonts/HandjetVariable]
  family: Handjet Variable Preview
  tasks:
    - .copy_fonts
    - .post.subset:
        # Remove all "empty" glyphs from the preview, except space (0020)
        remove_unicode_hex: [0000, 000D, 00A0, 2002, 2003, 2009, 202F]
    - .post.add_puas
    - .post.make_webfonts:
        optimize: false
        copy_fonts: False
    - "$ rm fonts/HandjetVF-Rg.ttf"
