# mrhandy 1.2.1
# ----------------------------------------------------
# A proprietary tooling to generate Handjet web fonts
# for the Rosetta foundry website. If you are updating
# or compiling Handjet fonts from sources you need not
# worry about this script/config file :)
# ----------------------------------------------------
- name: copy
  tasks:
    - $ mkdir fonts/HandjetVariable
    - $ cp fonts/Handjet[ELGR,ELSH,wght].ttf fonts/HandjetVariable/HandjetVF-All.ttf
    - .post.update_names:
        style_name: All
- name: desktop
  source: [fonts/HandjetVariable]
  family: [Handjet Variable]
  tasks:
    - .post.update_names:
        style_name: All
- name: web
  source: [fonts/HandjetVariable]
  family: [Handjet Variable Web]
  tasks:
    - .post.make_webfonts
- name: qa
  source: [fonts/HandjetVariable]
  tasks:
    - .test.check_fonts
